### PR TITLE
Prevents double subscription

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
As we added side effects to our action/mutation we discovered that live_ex dispatches event twice. I presume it's due to the fact that init is called once in LV and then another time in LC. 
Adding unsubscription first before subscribing again, to make sure to avoid that.

### CODE REVIEW

**Comment by PJUllrich** [comment]
Hello! Yes, I discovered this bug while bringing the [LiveEx Example](https://github.com/pjUllrich/live_ex_example) up to date. I realised that it doesn't make sense to subscribe both the parent LV and the child LV to the PubSub topic, since only the parent LV needs to receive the action messages in order to commit the mutations. This is why it isn't recommended anymore to call `init/2` in any child LVs or LCs anymore, but simply take the passed-down assigns and assign them to the child socket.

Here's how:
You only call `init/2` in the parent LV like [here](https://github.com/PJUllrich/live_ex_example/blob/master/lib/live_view_example_web/live/items/items_live.ex#L14)
And only assign the passed-down assigns to the child LV socket or in the LC like [here](https://github.com/PJUllrich/live_ex_example/blob/master/lib/live_view_example_web/live/items/count_live.ex#L12). Please note that the parent LV passes down the assigns as a string-based map, but we want to assign the assigns as atom-based keys. This is why I convert the string keys to atom keys before assigning them to the child socket.

In the example, I still encounter a bug where the child LV is destroyed and reloaded every time the state changes. I have to look into that some more.

**Comment by PJUllrich** [comment]
Oh, why looking through your test I realised that this bug is probably caused since the `mount/3` function of the LiveView is called twice. Once for the stateless mount and once for the stateful mount. This is why we double-subscribe to the topic. I added a check so that the LiveEx store subscribes to the PubSub topic only on the second mount.

You can check out the commit [here](https://github.com/PJUllrich/live_ex/commit/92f22422b310dccea7da3104a1ee47bf268072f1)

**Comment by Maxim-Filimonov** [comment]
Hm,
Okay so no more need to call init in LC ? 
I'll test latest version locally

**Comment by PJUllrich** [comment]
No, not in the child LCs and LVs. Only in the parent LV.

**Comment by Maxim-Filimonov** [comment]
@PJUllrich can you clarify has changed allowing to not init in child_view been merged? I see that README still says that we need to call init.

**Comment by PJUllrich** [comment]
I updated the Readme.

Basically, you child LV only takes the parameters which are passed down from the parent LV as the `session`. I'm not too happy about this since if the `session` changes (so, if the store's state changes), the entire child LV is re-rendered. Unfortunately, I don't have a good solution for that as of now, but I'll keep on thinking about this.

All this will be fixed once I move the store to its own `Agent` process. Then we can simply pass down the `pid` of the store and subscribe the child LV to any changes in the store. I'll think about this some more and will come up with a new version soon. 

Until then, please let me know if you find a better workaround around the re-rendering issue!

**Comment by Maxim-Filimonov** [comment]
Hm... I'm not sure you still would be able to dispatch. I just tried it in our code and we cannot dispatch as we get:
`key :live_ex_store_topic not found in: %{__context__: %{}`
Do you presume that we manually pass the topic to child components somehow?

**Pull request closed without merging**
