### PR TITLE
Update to LiveView 0.15+

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
Noticed that the library is not compatible with 0.15+ version of LV due to number of changes to pubsub and LV itself. Not sure what is the minimum version needed setting it 0.15 for now.

### CODE REVIEW

**Comment by PJUllrich** [comment]
I updated the library to `LiveView 1.15.7` before I saw this PR. Can we close this PR or are you missing something from the main repo?

**Comment by Maxim-Filimonov** [comment]
Do you want to replace Poison with Jason as I did here ? It seem to be the community way forward as it's superior parser.

**Comment by PJUllrich** [comment]
Sounds good! Will do.

**Comment by PJUllrich** [comment]
Poison was replaced with Jason in the main repo

**Pull request closed without merging**
